// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/crypto/coin/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/crypto/coin/[id].get').default>>>>
    }
    '/api/crypto/global': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/crypto/global.get').default>>>>
    }
    '/api/crypto/markets': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/crypto/markets.get').default>>>>
    }
    '/api/crypto/trending': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/crypto/trending.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}